services:
  - type: web
    name: tdx-combined-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python combined_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free 