"""Add is_confirmed to User

Revision ID: 151aae5fe8f4
Revises: 
Create Date: 2025-05-02 19:45:30.559034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151aae5fe8f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###
