# Generated by Django 5.2.1 on 2025-05-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('stock_symbols', models.CharField(help_text='Comma-separated list of 5 stock symbols', max_length=100)),
            ],
            options={
                'verbose_name': 'Stock Recommendation',
                'verbose_name_plural': 'Stock Recommendations',
                'ordering': ['-date'],
            },
        ),
    ]
