# Generated by Django 5.2.1 on 2025-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavsiye_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecommendation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
