# Generated by Django 5.2.1 on 2025-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavsiye_panel', '0002_stockrecommendation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecommendation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Tavsiye Videosu'),
        ),
    ]
