# Generated by Django 5.2.1 on 2025-05-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('change', models.FloatField()),
                ('target_price', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Düşük Risk'), ('MEDIUM', 'Orta Risk'), ('HIGH', 'Yüksek Risk')], max_length=10)),
                ('recommendation_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('change', models.FloatField()),
                ('volume', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
