# Generated by Django 5.2.1 on 2025-05-31 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedstock',
            options={},
        ),
        migrations.RemoveField(
            model_name='recommendedstock',
            name='change',
        ),
        migrations.AlterField(
            model_name='recommendedstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recommendedstock',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='recommendedstock',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Soru')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Cevap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='stockdb.recommendedstock')),
            ],
        ),
    ]
