# Generated by Django 5.0.2 on 2025-06-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdb', '0002_alter_recommendedstock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedstock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_images/', verbose_name='Hisse Fotoğrafı'),
        ),
    ]
