# Generated by Django 5.0.2 on 2025-06-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdb', '0003_recommendedstock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='stock_analysis_images/', verbose_name='PNG Fotoğraf')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('gemini_analysis', models.TextField(blank=True, null=True, verbose_name='Gemini Analizi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='Analiz Edildi mi?')),
            ],
            options={
                'verbose_name': 'Hisse Analiz Görseli',
                'verbose_name_plural': 'Hisse Analiz Görselleri',
            },
        ),
    ]
